### ISSUE TITLE
No issue, just a note.

### ISSUE THREAD

**Issue by j3rrey** [BrainMaestro/composer-git-hooks#87]
Found this package on the Laravel-News blog and immediately thought it looks very similar to grumphp.
Check it out maybe you can draw some inspiration:
https://github.com/phpro/grumphp

**Comment by BrainMaestro** [comment]
Hi @j3rrey, I had not seen that before actually. It is similar since it uses git hooks and pretty cool, but is much more than what this one does. This tool is very lightweight intentionally and I wouldn't want to grow the scope much more. Anyway, thanks for the note.

I'll close the issue now, but if you have more to discuss, feel free to reopen it.
